### ISSUE TITLE
Dismissible Moviment

### ISSUE THREAD

**Issue by Gabriel-Almeida-Ajax** [td-santos/Finance_App_Flutter#1]
Em lib\Widgets\CardMovimentacoesItem.dart

muda para:

lastItem == true
            ? Container(
      - - - > height: 0,
              )
            : Container()

está criando um bug na ultima movimentação na camada de Dismissible

**Comment by td-santos** [comment]
> Em lib\Widgets\CardMovimentacoesItem.dart
> 
> muda para:
> 
> lastItem == true
> ? Container(
> - - - > height: 0,
> )
> : Container()
> 
> está criando um bug na ultima movimentação na camada de Dismissible

Oi Gabriel , na verdade essa abordagem é proposital, pois em celulares com tela pequena , quando o usuário tem uma boa quantidade de movimentações na listagem, o último item fica atras do Navigation bar, por isso coloquei o container setado com altura 80 para que não ocorra isso.
